package pat2026;

import java.awt.*;
import java.io.File;
import java.io.FileNotFoundException;
import java.util.Scanner;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

  

    public class ManagerHome extends javax.swing.JFrame {

        private Worker[] workers;
        private int workerCount;

        public ManagerHome() {
            initComponents();
            DisplayDetails();
        }

        private void DisplayDetails() {
            DefaultTableModel model = (DefaultTableModel) tblWorker.getModel();
            model.setRowCount(0); // clears the empty placeholder row from the designer

            try {
                GetWorkers workerFetcher = new GetWorkers();

                if (workerFetcher.getWorkerData()) {
                    workers = workerFetcher.getWorkers();
                    workerCount = workerFetcher.getCount();

                    for (int i = 0; i < workerCount; i++) {
                        Object[] row = {
                            workers[i].getWorkerCode(),
                            workers[i].getName() + " " + workers[i].getSurname(),
                            workers[i].getStatus(),
                            "View / Edit",
                            "View / Edit"
                        };
                        model.addRow(row);
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "No workers have been captured yet.");
                }

            } catch (Exception e) {
                JOptionPane.showMessageDialog(this,
                        "Could not load worker records: " + e.getMessage());
            }

        }

        /**
         * This method is called from within the constructor to initialize the
         * form. WARNING: Do NOT modify this code. The content of this method is
         * always regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrlWorker = new javax.swing.JScrollPane();
        tblWorker = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        scrlWorker.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                scrlWorkerMouseClicked(evt);
            }
        });

        tblWorker.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Worker Code", "Name and Surname", "Status", "View Personal Details", "View Work"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblWorker.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblWorkerMouseClicked(evt);
            }
        });
        scrlWorker.setViewportView(tblWorker);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(scrlWorker, javax.swing.GroupLayout.PREFERRED_SIZE, 784, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(115, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(scrlWorker, javax.swing.GroupLayout.PREFERRED_SIZE, 471, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(117, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void scrlWorkerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_scrlWorkerMouseClicked

    }//GEN-LAST:event_scrlWorkerMouseClicked

    private void tblWorkerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblWorkerMouseClicked
       
        int row = tblWorker.rowAtPoint(evt.getPoint());
        int col = tblWorker.columnAtPoint(evt.getPoint());

        if (row < 0) {
            return; // clicked on empty space
        }

        String workerCode = tblWorker.getValueAt(row, 0).toString();

        if (col == 3) {
            btnWorkerDetails(workerCode);
        } else if (col == 4) {
            btnWorkdays(workerCode);
        }
    }

    private void btnWorkerDetails(String workerCode) {
        ViewEditWorkerInfo dialog = new ViewEditWorkerInfo(this, true, workerCode);
        dialog.setVisible(true);
        DisplayDetails(); // refresh after edits
    }

    private void btnWorkdays(String workerCode) {
        ViewEditWorkdays dialog = new ViewEditWorkdays(this, true, workerCode);
        dialog.setVisible(true);
        DisplayDetails();
    }//GEN-LAST:event_tblWorkerMouseClicked

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane scrlWorker;
    private javax.swing.JTable tblWorker;
    // End of variables declaration//GEN-END:variables
}
