package pat2026;

import java.awt.*;
import java.io.File;
import java.io.FileNotFoundException;
import java.util.Scanner;
import javax.swing.*;

public class ManagerHome extends javax.swing.JFrame {

    public ManagerHome() {
        initComponents();
    }

    private void addWorkerRow(String workerCode, String fullName, String status) {
        JPanel row = new JPanel(new GridLayout(1, 5, 5, 0)); 

        row.add(new JLabel(workerCode));
        row.add(new JLabel(fullName));
        row.add(new JLabel(status));

        JButton btnPersonal = new JButton("Personal Details");
        JButton btnWork = new JButton("Work");

        // Tag each button with the workerCode it belongs to, so you can
        // identify which worker was clicked once you wire up the listeners later
        btnPersonal.setActionCommand(workerCode);
        btnWork.setActionCommand(workerCode);

        row.add(btnPersonal);
        row.add(btnWork);

        row.setMaximumSize(new Dimension(Integer.MAX_VALUE, 35));
        pnlWorkerList.add(row);
    }

    private void loadWorkerList() {
        pnlWorkerList.removeAll();

    try (Scanner scFile = new Scanner(new File("WorkerDetails.txt"))) {
        while (scFile.hasNextLine()) {
            String line = scFile.nextLine();

            if (line.trim().isEmpty()) {
                continue; // skip blank separator lines between records
            }

            if (line.startsWith("WORKER CODE")) {
                // Line looks like: WORKER CODE: PIC003\t(Password: #003)
                String codePart = line.split("\t")[0];
                String workerCode = codePart.substring(codePart.indexOf(":") + 1).trim();

                scFile.nextLine(); // skip the "----" line

                String name = scFile.nextLine().substring(scFile.nextLine().indexOf(":") + 1).trim();
                // NOTE: placeholder — see fixed version below
            }
        }
    } catch (FileNotFoundException e) {
        System.out.println("WorkerDetails.txt not found.");
    }

    pnlWorkerList.revalidate();
    pnlWorkerList.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlWorkerList = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlWorkerList.setLayout(new javax.swing.BoxLayout(pnlWorkerList, javax.swing.BoxLayout.LINE_AXIS));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(pnlWorkerList, javax.swing.GroupLayout.PREFERRED_SIZE, 535, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(370, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(169, Short.MAX_VALUE)
                .addComponent(pnlWorkerList, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ManagerHome().setVisible(true));
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel pnlWorkerList;
    // End of variables declaration//GEN-END:variables
}
