package pat2026;

import java.time.Duration;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class ViewWork extends javax.swing.JDialog {

    private String workerCode;
    private Workday[] workdays;   // same order as the table rows
    private int workdayCount = 0; // how many rows the table has
    private DateTimeFormatter dateFormat = DateTimeFormatter.ofPattern("dd/MM/yyyy");

    public ViewWork(java.awt.Frame parent, boolean modal, String workerCode) {
        super(parent, modal);
        initComponents(); // generated by NetBeans GUI Builder
        this.workerCode = workerCode;
        displayTableDetails();
    }

    private void displayTableDetails() {
    DefaultTableModel model = (DefaultTableModel) tblViewWork.getModel();
    model.setRowCount(0); // clears the empty placeholder row from the designer

    try {
        GetWorkerWorkdays workdayFetcher = new GetWorkerWorkdays();

        if (workdayFetcher.getWorkdayData(workerCode)) {
            workdays = workdayFetcher.getWorkdays();
            workdayCount = workdayFetcher.getCount();

            for (int i = 0; i < workdayCount; i++) {
                Object[] row = {
                    workdays[i].getJobID(),
                    workdays[i].getDateWorked().format(dateFormat),
                    formatDuration(workdays[i].getHoursWorked()),
                    workdays[i].getTypeOfWork(),
                    workdays[i].getRowsCompleted(),
                    "View"
                };
                model.addRow(row);
            }
        } else {
            JOptionPane.showMessageDialog(this, "No workdays have been logged yet.");
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this,
                "Could not load workday records: " + e.getMessage());
    }
}

    // Short form for the table, e.g. "6h 0m"
    private String formatDuration(Duration duration) {
        return duration.toHours() + "h " + duration.toMinutesPart() + "m";
    }

    // Long form for the details box, e.g. "6 hour(s) 0 minute(s)"
    private String formatDurationLong(Duration duration) {
        return duration.toHours() + " hour(s) " + duration.toMinutesPart() + " minute(s)";
    }

    // In NetBeans: right-click tblViewWork > Events > Mouse > mouseClicked
    private void tblViewWorkMouseClicked(java.awt.event.MouseEvent evt) {
        int row = tblViewWork.getSelectedRow();
        int column = tblViewWork.getSelectedColumn();
        int lastColumn = tblViewWork.getColumnCount() - 1; // "See full Details" is the last column

        if (row >= 0 && column == lastColumn) {
            Workday day = workdays[row];

            String details = "JobID: " + day.getJobID()
                    + "\nDate Worked: " + day.getDateWorked().format(dateFormat)
                    + "\nStart Time: " + day.getStartTime()
                    + "\nEnd Time: " + day.getEndTime()
                    + "\nLunch Start: " + day.getLunchStart()
                    + "\nLunch End: " + day.getLunchEnd()
                    + "\nLunch Duration: " + formatDurationLong(day.getLunchDuration())
                    + "\nHours Worked (excl. lunch): " + formatDurationLong(day.getHoursWorked())
                    + "\nType of Work: " + day.getTypeOfWork()
                    + "\nRows Completed: " + day.getRowsCompleted();

            JOptionPane.showMessageDialog(this, details,
                    "Workday Details", JOptionPane.INFORMATION_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrlViewWork = new javax.swing.JScrollPane();
        tblViewWork = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tblViewWork.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "JobID", "Date", "Time Start", "Lunch Start", "Lunch End", "Time End", "Time worked", "Type of Work", "Rows Complete", "Type Of Work"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scrlViewWork.setViewportView(tblViewWork);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(scrlViewWork, javax.swing.GroupLayout.PREFERRED_SIZE, 986, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(scrlViewWork, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane scrlViewWork;
    private javax.swing.JTable tblViewWork;
    // End of variables declaration//GEN-END:variables
}
